/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ferreteria.vista;

import ferreteria.dao.IUsuariosDAO;
import ferreteria.dao.UsuariosDAO;
import ferreteria.tablas.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author ErickPalomo
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setTitle("Registro de Usuario");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbRegistro = new javax.swing.JLabel();
        LbNewUsuario = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LbIngresarContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnRegistrarse = new javax.swing.JButton();
        TxtContrasena = new javax.swing.JPasswordField();
        TxtconfirmarContra = new javax.swing.JPasswordField();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbRegistro.setText("Registrarse");

        LbNewUsuario.setText("Nuevo Usuario");

        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });

        LbIngresarContraseña.setText("Ingresar Contraseña");

        jLabel1.setText("Confirmar contraseña");

        BtnRegistrarse.setText("Registrarse");
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarseActionPerformed(evt);
            }
        });

        TxtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContrasenaActionPerformed(evt);
            }
        });

        TxtconfirmarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtconfirmarContraActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(LbRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                                .addComponent(BtnRegistrarse))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbNewUsuario)
                                    .addComponent(LbIngresarContraseña)
                                    .addComponent(jLabel1)
                                    .addComponent(TxtconfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LbRegistro)
                .addGap(44, 44, 44)
                .addComponent(LbNewUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbIngresarContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtconfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistrarse)
                    .addComponent(BtnCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
        this.TxtContrasena.requestFocus();
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarseActionPerformed
            // TODO add your handling code here:
             String miss1 = new String(this.TxtContrasena.getPassword());
        String miss2 = new String(this.TxtconfirmarContra.getPassword());
        String usuario1 =this.TxtUsuario.getText();
        if(usuario1.isEmpty()){
            JOptionPane.showMessageDialog(this, "El usuario no puede quedar vacio\nIngresa un valor valido ");
            this.TxtUsuario.requestFocus();
        }else if(miss1.isEmpty()&&miss2.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes completar todos los campos ");
            this.TxtContrasena.requestFocus();
        }
        
        else if(!(miss1.equals(miss2))){
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden ");
            this.TxtconfirmarContra.setText("");
            this.TxtconfirmarContra.requestFocus();
        }else{
            IUsuariosDAO usuariosDAO = new UsuariosDAO();
            Usuarios usuario = new Usuarios(usuario1,miss2);
           boolean exito = usuariosDAO.registrarUsuario(usuario);
if (exito) {
    JOptionPane.showMessageDialog(this, "Datos validados!");
    Principal login = new Principal();
    login.setVisible(true);
    this.dispose();
} else {
    JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario\nNombre de usuario ya registrado");
}
    }//GEN-LAST:event_BtnRegistrarseActionPerformed
}
    private void TxtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContrasenaActionPerformed
this.TxtconfirmarContra.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContrasenaActionPerformed

    private void TxtconfirmarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtconfirmarContraActionPerformed
this.BtnRegistrarse.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_TxtconfirmarContraActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        Principal login = new Principal();
            login.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JLabel LbIngresarContraseña;
    private javax.swing.JLabel LbNewUsuario;
    private javax.swing.JLabel LbRegistro;
    private javax.swing.JPasswordField TxtContrasena;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JPasswordField TxtconfirmarContra;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
